/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkplaceIndexRouteImport } from './routes/workplace-index'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as SalariesIndexRouteImport } from './routes/salaries.index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as ToolsSalaryCalculatorRouteImport } from './routes/tools.salary-calculator'
import { Route as SalariesHeatmapRouteImport } from './routes/salaries.heatmap'
import { Route as CompaniesSlugRouteImport } from './routes/companies.$slug'

const WorkplaceIndexRoute = WorkplaceIndexRouteImport.update({
  id: '/workplace-index',
  path: '/workplace-index',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalariesIndexRoute = SalariesIndexRouteImport.update({
  id: '/salaries/',
  path: '/salaries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSalaryCalculatorRoute = ToolsSalaryCalculatorRouteImport.update({
  id: '/tools/salary-calculator',
  path: '/tools/salary-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const SalariesHeatmapRoute = SalariesHeatmapRouteImport.update({
  id: '/salaries/heatmap',
  path: '/salaries/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/interviews': typeof InterviewsRoute
  '/jobs': typeof JobsRoute
  '/offers': typeof OffersRoute
  '/reviews': typeof ReviewsRoute
  '/saved': typeof SavedRoute
  '/workplace-index': typeof WorkplaceIndexRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/salaries/heatmap': typeof SalariesHeatmapRoute
  '/tools/salary-calculator': typeof ToolsSalaryCalculatorRoute
  '/companies/': typeof CompaniesIndexRoute
  '/salaries/': typeof SalariesIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/interviews': typeof InterviewsRoute
  '/jobs': typeof JobsRoute
  '/offers': typeof OffersRoute
  '/reviews': typeof ReviewsRoute
  '/saved': typeof SavedRoute
  '/workplace-index': typeof WorkplaceIndexRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/salaries/heatmap': typeof SalariesHeatmapRoute
  '/tools/salary-calculator': typeof ToolsSalaryCalculatorRoute
  '/companies': typeof CompaniesIndexRoute
  '/salaries': typeof SalariesIndexRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/interviews': typeof InterviewsRoute
  '/jobs': typeof JobsRoute
  '/offers': typeof OffersRoute
  '/reviews': typeof ReviewsRoute
  '/saved': typeof SavedRoute
  '/workplace-index': typeof WorkplaceIndexRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/salaries/heatmap': typeof SalariesHeatmapRoute
  '/tools/salary-calculator': typeof ToolsSalaryCalculatorRoute
  '/companies/': typeof CompaniesIndexRoute
  '/salaries/': typeof SalariesIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/compare'
    | '/interviews'
    | '/jobs'
    | '/offers'
    | '/reviews'
    | '/saved'
    | '/workplace-index'
    | '/companies/$slug'
    | '/salaries/heatmap'
    | '/tools/salary-calculator'
    | '/companies/'
    | '/salaries/'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/compare'
    | '/interviews'
    | '/jobs'
    | '/offers'
    | '/reviews'
    | '/saved'
    | '/workplace-index'
    | '/companies/$slug'
    | '/salaries/heatmap'
    | '/tools/salary-calculator'
    | '/companies'
    | '/salaries'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/compare'
    | '/interviews'
    | '/jobs'
    | '/offers'
    | '/reviews'
    | '/saved'
    | '/workplace-index'
    | '/companies/$slug'
    | '/salaries/heatmap'
    | '/tools/salary-calculator'
    | '/companies/'
    | '/salaries/'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  CompareRoute: typeof CompareRoute
  InterviewsRoute: typeof InterviewsRoute
  JobsRoute: typeof JobsRoute
  OffersRoute: typeof OffersRoute
  ReviewsRoute: typeof ReviewsRoute
  SavedRoute: typeof SavedRoute
  WorkplaceIndexRoute: typeof WorkplaceIndexRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
  SalariesHeatmapRoute: typeof SalariesHeatmapRoute
  ToolsSalaryCalculatorRoute: typeof ToolsSalaryCalculatorRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  SalariesIndexRoute: typeof SalariesIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workplace-index': {
      id: '/workplace-index'
      path: '/workplace-index'
      fullPath: '/workplace-index'
      preLoaderRoute: typeof WorkplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/': {
      id: '/salaries/'
      path: '/salaries'
      fullPath: '/salaries/'
      preLoaderRoute: typeof SalariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/salary-calculator': {
      id: '/tools/salary-calculator'
      path: '/tools/salary-calculator'
      fullPath: '/tools/salary-calculator'
      preLoaderRoute: typeof ToolsSalaryCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/heatmap': {
      id: '/salaries/heatmap'
      path: '/salaries/heatmap'
      fullPath: '/salaries/heatmap'
      preLoaderRoute: typeof SalariesHeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  CompareRoute: CompareRoute,
  InterviewsRoute: InterviewsRoute,
  JobsRoute: JobsRoute,
  OffersRoute: OffersRoute,
  ReviewsRoute: ReviewsRoute,
  SavedRoute: SavedRoute,
  WorkplaceIndexRoute: WorkplaceIndexRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
  SalariesHeatmapRoute: SalariesHeatmapRoute,
  ToolsSalaryCalculatorRoute: ToolsSalaryCalculatorRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  SalariesIndexRoute: SalariesIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
